controllers/ValidateController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Checklog;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use app\models\CheckForm;
use app\models\ClaimForm;
use app\models\UseForm;

use yii\filters\AccessControl;
use app\filters\AccessRule;
use app\models\User;
use app\models\Validate;
class ValidateController extends Controller
{
    const STATUS_SEND   = 2;
    const STATUS_ACTIVE = 10;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','claim','use','fail'],
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'rules' => [
                    [
                        'actions' => ['index','claim','use','fail'],
                        'allow' => true,
                        'roles' => [User::ROLE_ADMIN,User::ROLE_USER],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (!parent::beforeAction($action)) {
            return false;
        }

        if(!User::getLoginLock()){
            Yii::$app->user->logout();
            return $this->goHome();
        }

        return true; 
    }

    /**
     * 输入邀请码
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new CheckForm();

        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * 校验邀请码
     * @return mixed
     */
    public function actionCheck()
    {
        $request = Yii::$app->request;

        $inviteCode = $request->post('CheckForm')['inviteCode'];
        $model = new Validate();

        //记录日志
        Checklog::addLog('check', $inviteCode);
        
        $response = $model->checkInvite($inviteCode);
        
	    if($response['ret'] == 0){
            $data = $response['data'];
            if(\Yii::$app->user->identity->region != 'SuperAdmin' && \Yii::$app->user->identity->region != $data->region){
                return $this->render('fail', ['inviteCode' => $inviteCode]);
            }

            if($data->status != self::STATUS_ACTIVE && $data->status != self::STATUS_SEND){
                return $this->render('fail', ['inviteCode' => $inviteCode]);
            }
            
	        if($data->status == self::STATUS_SEND && (strtotime($data->send_at) + $data->claim_val * 3600) > time()){
                $model = new ClaimForm();
                return $this->render('claim', [
                    'model' => $model,
                    'inviteCode' => $inviteCode,
                ]);
            }elseif($data->status == self::STATUS_ACTIVE && (strtotime($data->activated_at) + $data->use_val * 3600) > time()){
                $user_id = $data->claimer_id;
                $model = new UseForm();
                return $this->render('use', [
                    'model' => $model,
                    'inviteCode' => $inviteCode,
                    'userID' =>$user_id,
                ]);
            }else{
                return $this->render('fail', ['inviteCode' => $inviteCode]);
            }
        }
        
        if(isset($response['ret'])){
            return $this->render('fail', ['inviteCode' => $inviteCode]);
        }
        //return $this->render('fail', ['inviteCode' => $inviteCode]);
        return $this->render('../site/error',['name' => 'Error', 'message' => 'Service error. Please contact Front of House support if the problem persists.']);
    }

    /**
     * claim邀请码
     * @return mixed
     */
    public function actionClaim()
    {
        $request = Yii::$app->request;

        $email = $request->post('email');
        $inviteCode = $request->post('inviteCode');

        $model = new Validate();

        //校验邮箱和邀请码格式
        if(!$model->isEmail($email) || !$model->isInviteCode($inviteCode)){
            return false;
        }
        
        $result = $model->getUserID($email);
        $user_id = 0;
	    if($result->ret == 1){
            $user_id = $result->data;
        }else{
            return $model->retJson('', 2, 'There is no active OnePlus account associated with this email. Please register at account.oneplus.net first.');
        }

        $response = $model->checkInvite($inviteCode);
        if($response['ret'] == 0){
            $data = $response['data'];
            if(\Yii::$app->user->identity->region != 'SuperAdmin' && \Yii::$app->user->identity->region != $data->region){
                return $this->render('fail', ['inviteCode' => $inviteCode]);
            }
            if($data->status != self::STATUS_SEND || (strtotime($data->send_at) + $data->claim_val * 3600) < time()){
                return $this->render('fail', ['inviteCode' => $inviteCode]);
            }
        }

        $claimResult = $model->claimInvite($inviteCode, $email, $user_id);
        if($claimResult['ret'] == 0){
            //记录日志
            Checklog::addLog('claim', $inviteCode, $email);
            
            return $model->retJson('', 0, 'Successfully claimed.');
        }else{
            return $model->retJson('', 1, 'Failed to claim invite. Please claim the invite manually at invites.oneplus.net.');
        }
    }

    /**
     * Use邀请码
     * @return mixed
     */
    public function actionUse()
    {
        $request = Yii::$app->request;

        $userID = $request->post('userId');
        $inviteCode = $request->post('inviteCode');

        $model = new Validate();

        //校验邀请码格式
        if(!$model->isInviteCode($inviteCode)){
            return false;
        }

        $response = $model->checkInvite($inviteCode);
        if($response['ret'] == 0){
            $data = $response['data'];
            if(\Yii::$app->user->identity->region != 'SuperAdmin' && \Yii::$app->user->identity->region != $data->region){
                return $this->render('fail', ['inviteCode' => $inviteCode]);
            }
            if($data->status != self::STATUS_ACTIVE || (strtotime($data->activated_at) + $data->use_val * 3600) < time()){
                return $this->render('fail', ['inviteCode' => $inviteCode]);
            }
        }

        $useResult = $model->useInvite($inviteCode, $userID);
        if($useResult['ret'] == 0){
            //记录日志
            Checklog::addLog('use', $inviteCode);

            return $model->retJson('', 0, 'Successfully set to used.');
        }else{
            return $model->retJson('', 1, 'Failed to set invite to used. Please try again later.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap">
    <div class="container">
        <?php
        NavBar::begin([
            'brandLabel' => '',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse',
            ],
        ]);
        /*echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'About', 'url' => ['/site/about']],
                ['label' => 'Contact', 'url' => ['/site/contact']],
                [
                    'label' => 'Status',
                    'items' => [
                        ['label' => 'View', 'url' => ['/status/index']],
                        ['label' => 'Create', 'url' => ['/status/create']],
                    ],
                ],
                Yii::$app->user->isGuest ?
                    ['label' => 'Login', 'url' => ['/site/login']] :
                    [
                        'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                        'url' => ['/site/logout'],
                        'linkOptions' => ['data-method' => 'post']
                    ],
            ],
        ]);*/
        if (Yii::$app->user->isGuest) {
            $navItems = [];
            array_push($navItems,['label' => 'Sign In', 'url' => ['/user/login']]/*,['label' => 'Sign Up', 'url' => ['/user/register']]*/);
        } else {
            $navItems=[
                ['label' => 'Validate Invites', 'url' => ['/validate/index']]
            ];
            if(Yii::$app->user->identity->isAdmin){
                array_push($navItems,['label' => 'Manage Users',
                'url' => ['/user/admin'],
                //'linkOptions' => ['data-method' => 'post']
                ]);
            }
            /*array_push($navItems,['label' => 'Logout (' . Yii::$app->user->identity->username . ' | '.Yii::$app->user->identity->region.')',
                'url' => ['/site/logout'],
                'linkOptions' => ['data-method' => 'post']]
            );*/
        }
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $navItems,
        ]);
        NavBar::end();
        ?>
    </div>
    

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <?php if(!Yii::$app->user->isGuest){ ?>
            <p class="pull-right"><a href="/site/logout" data-method="post">Logout (<?php echo Yii::$app->user->identity->username . ' | '.Yii::$app->user->identity->region ?>)</a></p>
        <?php } ?>
        <p class="pull-left">&copy; OnePlus <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
<?=Html::jsFile('@web/scripts/main.js')?>
</body>
</html>
<?php $this->endPage() ?>